const truths = [
  "Is it true you still suck your thumb because you think it tastes like chicken?",
  "Is it true that you smell your own farts?",
  "Is it true you eat your boogers?",
  "When was the last time you lied?",
  "When was the last time you cried?",
  "What's your biggest fear?",
  "What's your biggest fantasy?", 
  "Who's the last person you searched on Instagram?",
  "What's the strangest thing you've ever eaten?",
  "What's your relationship dealbreaker?",
  "What's a secret you've never told anyone?",
  "Do you have a hidden talent?",
  "Who was your first celebrity crush?",
  "Have you ever cheated in an exam?",
  "If you were going to be on a reality TV show, which would it be?",
  "What's your biggest insecurity?",
  "What's the biggest mistake you've ever made?",
  "What's one thing you hate people knowing about you?",
  "What's the worst thing anyone's ever done to you?",
  "What's the best thing anyone's ever done for you?",
  "What's your worst habit?",
  "What's the biggest misconception about you?",
  "What's one thing you wish people knew about you?",
  "Why did your last relationship break down?",
  "What's the best piece of advice you've been given?",
  "What's the most you've spent on a night out?",
  "Have you ever returned or re-gifted a present?",
  "Do you have a favourite sibling?",
  "What have you purchased that's been the biggest waste of money?",
  "How would you rate your looks on a scale of 1 to 10?",
  "What celebrity do you look up to?",
  "If you could be one celebrity for a day, who would it be?",
  "If you could do any job in the world, what would it be?",
  "What's your dream life?",
  "What do you value the most - money, fame, success, friends, family, etc?",
  "What’s your biggest red flag?",
  "If you had to marry someone in this room, who would it be and why?",
  "What’s one movie you’re embarrassed to admit you enjoy?",
  "What music artist do you secretly think is overrated?",
  "What’s your most controversial political opinion?",
  "Name something you can’t live without",
  "Where do you think you’ll be in five years time?",
  "What's on your 'On Repeat' Spotify playlist right now?",
  "How well do you think you’d do in a horror movie?",
  "How many stuffed animals do you own?",
  "Did you ever get in trouble at school? And if so what for?",
  "Do you have any phobias?",
  "Who was the last person you kissed?",
  "If you could marry any celebrity, who would it be and why?",
  "What is your love language?",
  "Who in your phone book would you least like to call right now?",
  "Who is your 'The One That Got Away'?",
  "Do you have a celebrity lookalike?",
  "What are your five most-watched films?"

];

const dares = [
  "I dare you to eat a Peanut Butter and Mayonnaise Sandwich.",
  "I dare you to go outside and eat the first bug you find.",
  "I dare you to confess your darkest secret.",
  "I dare you to confess who you're crushing on.",
  "Try to juggle 3 things of the group's choice",
  "Show the most embarrassing photo on your phone",
  "Show the last five people you texted and what the messages said",
  "Let the rest of the group DM someone from your Instagram account",
  "Do 100 squats",
  "Let the group look in your Instagram DMs",
  "Show us your screen time report",
  "Keep three ice cubes in your mouth until they melt",
  "Yell out the first word that comes to your mind",
  "Keep your eyes closed until it's your go again",
  "Empty out your wallet/purse and show everyone what's inside",
  "Pretend to be the person to your right for 10 minutes",
  "Eat a snack without using your hands",
  "Whisper a secret to the person on your left",
  "Say two honest things about everyone else in the group",
  "Tell the saddest story you know",
  "Hold your drink with two hands for the rest of the evening",
  "Put on make-up without a mirror and leave it like that for the rest of the game",
  "Neck the drink (responsibly) of the person on your right",
  "Say yes to everything for the next 1 minute",
  "Show your favourite picture of yourself",
  "Post a TikTok draft",
  "Make a rap about your favourite book",
  "Do 50 push ups",
  "Reveal what you think everyone in the group will be up to in five years time",
  "Give everyone in the room a backhanded compliment",
  "Let the group style your hair and leave it that way for the entire game",
  "Only talk in whispers for the next 10 minutes",
  "Say a secret about someone in the room but not reveal their name"
];

document.getElementById('truthBtn').addEventListener('click', () => {
  const randomTruth = truths[Math.floor(Math.random() * truths.length)];
  document.getElementById('prompt').textContent = randomTruth;
});

document.getElementById('dareBtn').addEventListener('click', () => {
  const randomDare = dares[Math.floor(Math.random() * dares.length)];
  document.getElementById('prompt').textContent = randomDare;
});